### ISSUE TITLE
rps|scissor

### ISSUE THREAD

**Issue by sarkartanmay393** [MarkisDev/rock-paper-scissors#16]

**Comment by MarkisDev** [comment]
Congratulations! You won! :tada:

**Comment by MarkisDev** [comment]
Oops! This was a draw! :eyes:

**Comment by MarkisDev** [comment]
Oops! This was a draw! :eyes:

**Comment by MarkisDev** [comment]
Oops! This was a draw! :eyes:

**Comment by MarkisDev** [comment]
Uh-Oh! You lost! :eyes:
 Computer played rock
