### ISSUE TITLE
rps|rock

### ISSUE THREAD

**Issue by Ifycode** [MarkisDev/rock-paper-scissors#78]
Choose rock this time please... 🙏

**Comment by Ifycode** [comment]
Better than a loss this time. But what makes it a draw? Can this be explained in the readme @MarkisDev?

**Comment by MarkisDev** [comment]
Hey @Ifycode,
Draw essentially means both you and the computer played the same move!

In this case, the computer and you have both played rock which led to a draw :)

**Comment by Ifycode** [comment]
Oh... I see. I also went to read about the game. [This particular resource](https://thegeniusofplay.org/genius/play-ideas-tips/play-ideas/rock-paper-scissors.aspx#.Y1NhpuzMKdY) explains it this way: Rock crushes scissors, scissors cut paper, and paper covers rock. So I understand the game now.

I'm not someone who really likes or understands how to play games. But this caught my attention because it involves git/github. I love it. Thank you for answering my question.

Can I send a pull request with content to help those who have no idea of how the game works? @MarkisDev
